artifacts:
  aftercourt-documents-dataset:
    path: data/raw/final_raw_data.csv
    type: dataset
    desc: The raw dataset containing document text, metedata and labels. This is the starting point of the pipeline, used in the prepare stage to create train/test splits for each target.
  tf-idf-vectorizer:
    path: models/vectorizers/vectorizer.dill
    type: model
    desc: TF-IDF vectorizer for text featurization. Shared across documents. Therefore the stage for fitting vectorizer is not parameterized by target.

stages:
  prepare:
    cmd: python src/prepare/prepare.py data/raw/final_raw_data.csv
    deps:
    - data/raw/final_raw_data.csv
    - src/prepare/prepare.py
    params:
    - prepare.target
    - prepare.${prepare.target}
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared/${prepare.target}/test.csv
    - data/prepared/${prepare.target}/train.csv
  tokenize:
    frozen: true
    cmd: python src/tokenization/tokenization_ladung.py data/prepared/${prepare.target} data/tokenized/${prepare.target}
    deps:
    - src/tokenization/tokenization_ladung.py
    - data/prepared/${prepare.target}/train.csv
    - data/prepared/${prepare.target}/test.csv
    params:
    - prepare.target
    outs:
    - data/tokenized/${prepare.target}/train.csv
    - data/tokenized/${prepare.target}/test.csv
  fit_vectorizer:
    desc: Fit a shared TF-IDF vectorizer on ladung training data. Shared across all targets, does not depend on prepare.target.
    cmd: python src/featurazition/fit_vectorizer.py data/prepared/ladung/train.csv models/vectorizers/vectorizer.dill
    deps:
    - src/featurazition/fit_vectorizer.py
    - data/prepared/ladung/train.csv
    params:
    - fit_vectorizer.seed
    - fit_vectorizer.vectorizer
    outs:
    - models/vectorizers/vectorizer.dill
  featurize:
    cmd: python src/featurazition/featurazition.py data/prepared/${prepare.target} models/vectorizers/vectorizer.dill data/featurized/${prepare.target}
    deps:
    - src/featurazition/featurazition.py
    - data/prepared/${prepare.target}/train.csv
    - data/prepared/${prepare.target}/test.csv
    - models/vectorizers/vectorizer.dill
    params:
    - prepare.target
    - prepare.${prepare.target}.target_col
    outs:
    - data/featurized/${prepare.target}/train_features.npz
    - data/featurized/${prepare.target}/train_labels.npy
    - data/featurized/${prepare.target}/test_features.npz
    - data/featurized/${prepare.target}/test_labels.npy

