stages:
  prepare_ladung:
    cmd: python src/prepare/prepare_ladung.py data/raw/final_raw_data.csv
    deps:
    - data/raw/final_raw_data.csv
    - src/prepare/prepare_ladung.py
    params:
    - prepare.ladung
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared/ladung/test.csv
    - data/prepared/ladung/train.csv
  tokenize_ladung:
    cmd: python src/tokenization/tokenization_ladung.py data/prepared/ladung data/tokenized/ladung
    deps:
    - src/tokenization/tokenization_ladung.py
    - data/prepared/ladung/train.csv
    - data/prepared/ladung/test.csv
    outs:
    - data/tokenized/ladung/train.csv
    - data/tokenized/ladung/test.csv