prepare:
  split: 0.20
  seed: 42
  ladung:
    aftercourt_preprocessing:
      normalize_whitespace: True
      remove_short_lines: True
      short_line_threshold: 3
      remove_html_tags: True
      lowercase: True
    target_col: is_ladung

  pfub:
    aftercourt_preprocessing:
      normalize_whitespace: True
      remove_short_lines: True
      short_line_threshold: 3
      remove_html_tags: True
      lowercase: True
    target_col: is_pfub

featurazition:
  seed: 1
  vectorizer:
    max_features: 200
    ngram_range_min: 1
    ngram_range_max: 1
    norm: l2
    min_df: 2
    max_df: 0.95
    lowercase: False