prepare:
  target: ladung
  split: 0.20
  seed: 42
  ladung:
    aftercourt_preprocessing:
      normalize_whitespace: true
      remove_short_lines: true
      short_line_threshold: 3
      remove_html_tags: true
      lowercase: true
    target_col: is_ladung

  pfub:
    aftercourt_preprocessing:
      normalize_whitespace: true
      remove_short_lines: true
      short_line_threshold: 3
      remove_html_tags: true
      lowercase: true
    target_col: is_pfub

fit_vectorizer:
  seed: 1
  vectorizer:
    max_features: 200
    ngram_range_min: 1
    ngram_range_max: 1
    norm: l2
    min_df: 2
    max_df: 0.95
    lowercase: false

train:
  seed: 42
  classifier:
    n_estimators: 100
    random_state: 42

evaluate:
  threshold: 0.9
